run:
  modules-download-mode: readonly
linters:
  enable:
    - gofmt
    - goimports
    # TODO(jan25): Enable these along with all violation fixes
    # - golint
    # - govet
linters-settings:
  goimports:
    local-prefixes: github.com/spinnaker/spin